### ISSUE TITLE
Regression: Home page art is distracting on dark theme due to white background

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Community-website#52]
I just played around with this on my work laptop and personal desktop machine and my only suggestion is pretty much what Sylveon said about the image. Other than that it works as expected. a nice bonus is that it is dynamic - if you change the setting on your computer the theme will change without refreshing the page.

_Originally posted by @Danielx64 in https://github.com/Microsoft-community/Community-website/pull/49#issuecomment-669096465_

Dark mode query: https://twitter.com/equinusocio/status/1292814528770703360

**Comment by torchgm** [comment]
Since nobody's bothered with this issue, how about the following:
![hero](https://user-images.githubusercontent.com/31840547/127013670-25a9c758-2e1e-46bf-b387-fa7464ecfff7.png)

effectively just removing the background and adding a white outline around things (since the source isn't clean and there appears to be no transparent version available), also imho it helps it stand out a little better:
![image](https://user-images.githubusercontent.com/31840547/127013834-a55d03c8-2e2c-4802-8025-e7a16f87d27d.png)

**Comment by dAKirby309** [comment]
Seems good to me.

**Comment by Erisa** [comment]
@torchgm If you could make a totally dark theme version of the image, we can use the `media=` tag mentioned in the original comment to replace it on the fly based on the users theme

**Comment by torchgm** [comment]
![image](https://user-images.githubusercontent.com/31840547/127018993-ad487c2d-4580-47a9-a8fa-8cc1f8663db3.png)
I tried but the image has been disgustingly jpeggled to death so I either had to settle with a poor crop leaving white ickyness around the edge or really blurry edges

**Comment by Erisa** [comment]
Gotcha! In that case I agree with the outline you created! That would pretty much resolve the problem.

**Comment by Jasius** [comment]
Oh, hello

**Comment by torchgm** [comment]
Hi yes this is your issue - you don't happen to have the original sauce for the artwork? We've found a few that are better but it'd be nice to know where it originally came from

**Comment by torchgm** [comment]
![image](https://user-images.githubusercontent.com/31840547/128006047-d0642e00-5e10-43b0-9374-5a5273b50215.png)
Although to be honest this is probably good enough
